create schema cars;
-- READ DATA--
select* from cars.`car dekho`;
 
 -- TOTAL COUNTS OF CARS--
select count(*) from cars.`car dekho`;

--  HOW MANY CARS WILL BE AVAILABLE IN 2032 --
SELECT count(*) FROM CARS.`CAR DEKHO` WHERE YEAR = 2023;

-- HOW MANY CARS WILL BE AVAILABLE IN 2020,2021,2022? ---
SELECT count(*) FROM CARS.`CAR DEKHO` WHERE YEAR = 2020;
SELECT count(*) FROM CARS.`CAR DEKHO` WHERE YEAR = 2021;
SELECT count(*) FROM CARS.`CAR DEKHO` WHERE YEAR = 2022;

-- ANOTHER METHOD TO FIND THIS ---
SELECT COUNT(*) FROM CARS.`CAR DEKHO` WHERE YEAR IN (2020,2021,2022) GROUP BY YEAR;


-- TOTAL OF ALL CARS BY YEAR --
SELECT YEAR, COUNT(YEAR) FROM CARS.`CAR DEKHO` GROUP BY YEAR;


-- HOW MANY DIESEL CARS WILL BE THERE IN 2020? --
SELECT COUNT(*) FROM CARS.`CAR DEKHO` WHERE YEAR = 2020 AND FUEL ='DIESEL';


-- HOW MANY PETROL CARS WILL BE THERE IN 2020? --
SELECT COUNT(*) FROM CARS.`CAR DEKHO` WHERE YEAR = 2020 AND FUEL ='PETROL';


-- HOW MANY PETROL CARS BY YEARS?-- 
select YEAR, COUNT(YEAR) FROM CARS.`CAR DEKHO` WHERE FUEL = 'PETROL' GROUP BY YEAR;

-- DIESEL CARS BY YEAR --
select YEAR, COUNT(YEAR) FROM CARS.`CAR DEKHO` WHERE FUEL = 'DIESEL' GROUP BY YEAR;


-- CNG CARS BY YEAR --
select YEAR, COUNT(YEAR) FROM CARS.`CAR DEKHO` WHERE FUEL = 'CNG' GROUP BY YEAR;


-- YEARS HAVING MORE THAN 100 CARS --
SELECT YEAR, COUNT(YEAR) FROM CARS.`CAR DEKHO` GROUP BY YEAR HAVING COUNT(YEAR) > 100;


-- YEARS HAVING LESS THAN 50 CARS --
SELECT YEAR, COUNT(YEAR) FROM CARS.`CAR DEKHO` GROUP BY YEAR HAVING COUNT(YEAR) <50;



-- COUNT OF CARS BETWEEN 2015 AND 2023 --
SELECT COUNT(*) FROM CARS.`CAR DEKHO` WHERE YEAR  BETWEEN 2015 AND 2023;





